# Generated by Django 5.0.1 on 2024-02-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
